import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowUpRight, Building2, CheckCircle2, MapPin } from "lucide-react";
import { toast } from "sonner";
import { api } from "../lib/api";
import { useAuth } from "../context/AuthContext";

export default function JobDetails(){
  const {id}=useParams(); const {user}=useAuth(); const nav=useNavigate();
  const [job,setJob]=useState(null); const [profile,setProfile]=useState(null); const [coverLetter,setCoverLetter]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{api.get(`/jobs/${id}`).then(r=>setJob(r.data)); if(user?.role==="candidate") api.get("/users/me").then(r=>setProfile(r.data)).catch(()=>{});},[id,user?.role]);
  if(!job) return <section className="container page-section"><div className="skeleton detail-skeleton"/></section>;
  const apply=async()=>{ if(!user){nav("/login");return;} if(user.role!=="candidate"){toast.error("Candidate account required");return;} if(!profile?.resume?.url){toast.error("Upload your resume in Profile first");nav("/profile");return;} setBusy(true);try{await api.post("/applications",{jobId:job._id,recruiterId:job.recruiterId,recruiterEmail:job.recruiterEmail,jobTitle:job.title,companyName:job.companyName,candidateName:profile.name,candidateEmail:profile.email,resumeUrl:profile.resume.url,skills:profile.skills,requiredSkills:job.skills,coverLetter});toast.success("Application sent");}catch(e){toast.error(e.response?.data?.message||"Could not apply");}finally{setBusy(false);}};
  return <section className="container page-section"><div className="detail-layout"><article className="detail-main"><div className="detail-title"><div className="company-icon xl"><Building2 size={28}/></div><div><p className="eyebrow">{job.companyName}</p><h1>{job.title}</h1><div className="job-meta"><span><MapPin size={15}/>{job.location||"Flexible"}</span><span>{job.workplaceType}</span><span>{job.employmentType}</span></div></div></div><div className="divider"/><section><h2>About the role</h2><p className="prose">{job.description}</p></section><section><h2>What you’ll do</h2><div className="check-list">{job.responsibilities?.map(x=><p key={x}><CheckCircle2 size={17}/>{x}</p>)}</div></section><section><h2>What we’re looking for</h2><div className="check-list">{job.requirements?.map(x=><p key={x}><CheckCircle2 size={17}/>{x}</p>)}</div></section><section><h2>Skills</h2><div className="skill-row">{job.skills?.map(x=><span className="pill" key={x}>{x}</span>)}</div></section></article><aside className="apply-card"><div><p className="eyebrow">Apply now</p><h3>{job.applyMode==="external"?"Continue to company":"Use your JobNova profile"}</h3></div>{job.applyMode!=="external"&&<textarea rows="6" placeholder="Optional cover note..." value={coverLetter} onChange={e=>setCoverLetter(e.target.value)}/>} {(job.applyMode==="internal"||job.applyMode==="both")&&<button className="btn primary large full" onClick={apply} disabled={busy}>{busy?"Sending...":"Apply with profile"}</button>}{(job.applyMode==="external"||job.applyMode==="both")&&<a className="btn glass large full" href={job.externalApplyUrl} target="_blank" rel="noreferrer">Company application <ArrowUpRight size={17}/></a>}<small>Your saved resume and skills are shared only when you submit an internal application.</small></aside></div></section>
}
