import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { api } from "../lib/api";
import { useAuth } from "../context/AuthContext";

export default function PostJob(){
  const {user}=useAuth(); const nav=useNavigate();
  const [f,setF]=useState({companyName:user?.companyName||"",title:"",field:"Software Engineering",description:"",responsibilities:[],requirements:[],skills:[],employmentType:"Full-time",workplaceType:"On-site",location:"",experienceLevel:"Fresher",applyMode:"internal",externalApplyUrl:""});
  const set=(k,v)=>setF({...f,[k]:v});
  const submit=async e=>{e.preventDefault();try{await api.post("/jobs",f);toast.success("Job published");nav("/recruiter");}catch(err){toast.error(err.response?.data?.message||"Could not publish");}};
  const arr=(k,v)=>set(k,v.split("\n").map(x=>x.trim()).filter(Boolean));
  return <section className="container page-section narrow"><div className="page-hero compact"><p className="eyebrow">Create opportunity</p><h1>Post a new role</h1></div><form className="panel form-stack" onSubmit={submit}><div className="two-col"><label>Company<input required value={f.companyName} onChange={e=>set("companyName",e.target.value)}/></label><label>Job title<input required value={f.title} onChange={e=>set("title",e.target.value)}/></label></div><div className="two-col"><label>Field<input required value={f.field} onChange={e=>set("field",e.target.value)}/></label><label>Location<input value={f.location} onChange={e=>set("location",e.target.value)}/></label></div><label>Description<textarea rows="7" required value={f.description} onChange={e=>set("description",e.target.value)}/></label><div className="two-col"><label>Responsibilities, one per line<textarea rows="6" onChange={e=>arr("responsibilities",e.target.value)}/></label><label>Requirements, one per line<textarea rows="6" onChange={e=>arr("requirements",e.target.value)}/></label></div><label>Skills, comma-separated<input value={f.skills.join(", ")} onChange={e=>set("skills",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/></label><div className="three-col"><label>Employment<select value={f.employmentType} onChange={e=>set("employmentType",e.target.value)}><option>Full-time</option><option>Part-time</option><option>Internship</option><option>Contract</option></select></label><label>Workplace<select value={f.workplaceType} onChange={e=>set("workplaceType",e.target.value)}><option>On-site</option><option>Remote</option><option>Hybrid</option></select></label><label>Experience<input value={f.experienceLevel} onChange={e=>set("experienceLevel",e.target.value)}/></label></div><label>Application mode<select value={f.applyMode} onChange={e=>set("applyMode",e.target.value)}><option value="internal">Apply inside JobNova</option><option value="external">External company portal</option><option value="both">Offer both options</option></select></label>{f.applyMode!=="internal"&&<label>Company application URL<input type="url" required value={f.externalApplyUrl} onChange={e=>set("externalApplyUrl",e.target.value)}/></label>}<button className="btn primary large">Publish job</button></form></section>
}
